{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  # The name of your ingress (set by Helm)
  name: {{ include "chart.fullname" . }}
  labels:
    # Standard chart labels
    {{- include "chart.labels" . | nindent 4 }}
  # Optional ingress annotations (for nginx, cert-manager, etc)
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  # Optional: specify ingress class (e.g. nginx, traefik)
  {{- with .Values.ingress.className }}
  ingressClassName: {{ . }}
  {{- end }}
  # Optional: enable HTTPS with TLS certificates
  {{- if .Values.ingress.tls }}
  tls:
    {{- range .Values.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  # Rules define which hosts and paths route to your service
  rules:
    {{- range .Values.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            {{- with .pathType }}
            pathType: {{ . }}
            {{- end }}
            backend:
              service:
                name: {{ include "chart.fullname" $ }}
                port:
                  number: {{ $.Values.service.port }}
          {{- end }}
    {{- end }}
{{- end }}
