apiVersion: v1
kind: Secret
metadata:
  name: {{ include "chart.fullname" . }}-secret
type: Opaque
stringData:
  DJANGO_SECRET_KEY: {{ .Values.env.DJANGO_SECRET_KEY | quote }}
  DATABASE_PASSWORD: {{ .Values.env.DATABASE_PASSWORD | quote }}
