apiVersion: v1
kind: Service
metadata:
  
  name: {{ include "bookcatalog.fullname" . }}
  labels:

    {{- include "bookcatalog.labels" . | nindent 4 }}
spec:

  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}     
      targetPort: 8000                    
      protocol: TCP
      name: http
  selector:

    {{- include "bookcatalog.selectorLabels" . | nindent 4 }}
